src/pages/loginPage/LoginForm.js, src/pages/loginPage/LoginPage.js, src/pages/loginPage/styled.js
* LoginPage
* LoginForm 
* Básico do CSS
=> Criação da página Login

src/pages/adressPage/AdressPage.js, src/pages/adressPage/styled.js
- Base do código da página;
- Endpoint 'Add Adress';
- Falta Material-UI.
=> Criação de Endereço

src/components/orders/OrderCard.js, src/pages/profilePage/ProfilePage.js, src/pages/upDateProfile/UpDateProfile.js, src/pages/upDateProfile/styled.js
quanta habilidade com material ui
=> atualizacao formato data e minima estilizacao

src/constants/urls.js, src/pages/adressPage/AdressPage.js, src/pages/adressPage/styled.js
Att Request Add Adress (new token)
=> Att Requisição AddAdress

src/constants/urls.js, src/global/GlobalState.js, src/pages/adressPage/AdressPage.js, src/pages/feedPage/FeedPage.js, src/pages/signUpPage/singUpForm/SingUpForm.js
=> global states get restaurants e BO nos tokens (importacao na mão)

src/components/orders/OrderCard.js, src/pages/loginPage/LoginForm.js
=> tokens do login() e ajuste do date moment

src/components/header/Header.js, src/global/GlobalState.js, src/pages/profilePage/ProfilePage.js, src/pages/upDateProfile/UpDateProfile.js, src/routes/coordinator.js
=> logica do header utilizando o global state

src/pages/adressPage/AdressPage.js
=> Condicional AdressPage

src/constants/colors.js, src/pages/feedPage/FeedPage.js, src/pages/feedPage/cardRestaurant/CardRestaurant.js
=> Feed laura

src/pages/feedPage/FeedPage.js, src/pages/feedPage/cardRestaurant/CardRestaurant.js
=> filtro de pesquisa por nome funcionando

src/hooks/useForm.js, src/pages/adressPage/AdressPage.js, src/pages/signUpPage/singUpForm/SingUpForm.js, src/pages/upDateProfile/UpDateProfile.js
=> inputs de address e profile ficam com infos do usuário

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/restaurantDetailsPage/productCard/styled.js, src/pages/restaurantDetailsPage/styled.js
=> Estilização pagina de detalhes

src/pages/adressPage/AdressPage.js, src/pages/profilePage/ProfilePage.js, src/pages/profilePage/styled.js
=> style do profile page(falta os cards de pedidos

src/components/header/styled.js, src/pages/adressPage/AdressPage.js, src/pages/feedPage/FeedPage.js, src/pages/loginPage/LoginForm.js, src/pages/profilePage/ProfilePage.js, src/pages/signUpPage/SignUpPage.js, src/pages/upDateProfile/UpDateProfile.js
=> Att Header, ajustes gerais Endereço

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js
=> apagando uma chave a mais

src/pages/cartPage/CartPage.js
=> descomentando uma função

src/components/footer/Footer.js, src/components/footer/styled.js, src/constants/urls.js, src/global/GlobalState.js, src/pages/adressPage/AdressPage.js, src/pages/adressPage/styled.js, src/pages/cartPage/CartPage.js, src/pages/cartPage/productOnCartPage/ProductOnCartPage.js, src/pages/feedPage/FeedPage.js, src/pages/feedPage/cardRestaurant/CardRestaurant.js, src/pages/feedPage/cardRestaurant/styled.js, src/pages/loginPage/LoginForm.js, src/pages/loginPage/LoginPage.js, src/pages/loginPage/styled.js, src/pages/profilePage/ProfilePage.js, src/pages/profilePage/styled.js, src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/restaurantDetailsPage/productCard/styled.js, src/pages/restaurantDetailsPage/styled.js, src/pages/signUpPage/SignUpPage.js, src/pages/signUpPage/singUpForm/SingUpForm.js, src/pages/signUpPage/singUpForm/styled.js, src/pages/signUpPage/styled.js, src/pages/upDateProfile/UpDateProfile.js, src/pages/upDateProfile/styled.js, src/styledApp.js
=> Organizando código e resolvendo problemas

src/components/footer/Footer.js, src/global/GlobalState.js, src/pages/adressPage/AdressPage.js, src/pages/cartPage/CartPage.js, src/pages/cartPage/productOnCartPage/ProductOnCartPage.js, src/pages/feedPage/FeedPage.js, src/pages/feedPage/cardRestaurant/CardRestaurant.js, src/pages/loginPage/LoginForm.js, src/pages/profilePage/ProfilePage.js, src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/signUpPage/SignUpPage.js, src/pages/upDateProfile/UpDateProfile.js
Correção de bugs e melhorias no código! 
Guud nite
=> Correção de bugs e melhorias no código

src/pages/adressPage/AdressPage.js
=> resolvendo bug input complement

src/pages/profilePage/ProfilePage.js
=> resolucao do loop infinito profile page

public/index.html, src/components/orders/OrderCard.js, src/components/orders/styled.js, src/pages/profilePage/ProfilePage.js
=> css do profile feita, fonte do site padronizada no index (roboto)

src/pages/feedPage/FeedPage.js, src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/modal/Modal.js, src/pages/restaurantDetailsPage/modal/styled.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js
=> Resolvendo bug filtro, Add modal

src/components/activeOrderCard/ActiveOrderCard.js, src/components/orders/OrderCard.js, src/global/GlobalState.js, src/pages/feedPage/FeedPage.js
=> lógica card de pedido andamento feita

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js
=> condição só um restaurante no carrinho

src/components/activeOrderCard/ActiveOrderCard.js, src/pages/feedPage/FeedPage.js
=> bugs resolvidos feed e activeorder

src/pages/profilePage/ProfilePage.js, src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js
=> correçao das quebras

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js
=> Sergio teste

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/restaurantDetailsPage/productCard/styled.js, src/pages/restaurantDetailsPage/styled.js
=> Estilização card

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js
=> organizando o codigo para fazer as funcoes do modal

src/pages/cartPage/CartPage.js, src/pages/cartPage/productOnCartPage/ProductOnCartPage.js, src/pages/cartPage/productOnCartPage/styled.js, src/pages/cartPage/styled.js, src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/restaurantDetailsPage/productCard/styled.js
=> Sabrina estlizacao pedido

src/components/activeOrderCard/ActiveOrderCard.js, src/components/activeOrderCard/style.js, src/components/footer/styled.js, src/constants/colors.js, src/constants/theme.js, src/pages/feedPage/FeedPage.js
=> card de activeorder feito, css pronto

src/global/GlobalState.js, src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/modal/Modal.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/restaurantDetailsPage/productCard/styled.js
=> Sergio modal functions

src/pages/restaurantDetailsPage/RestaurantDetailsPage.js, src/pages/restaurantDetailsPage/productCard/ProductCard.js, src/pages/restaurantDetailsPage/productCard/styled.js, src/pages/restaurantDetailsPage/styled.js, src/styledApp.js
=> ajustes page detalhes
